import { Tag } from 'antd';

const colors: Record<string, string> = {
  ready: 'success',
  healthy: 'success',
  succeeded: 'success',
  success: 'success',
  passed: 'success',
  fresh: 'success',
  confirmed: 'success',
  verified: 'success',
  running: 'processing',
  refreshing: 'processing',
  pending: 'processing',
  preparing: 'processing',
  testing: 'processing',
  queued: 'default',
  created: 'default',
  manual: 'default',
  scheduled: 'default',
  skipped: 'default',
  discovered: 'default',
  unknown: 'warning',
  degraded: 'warning',
  stale: 'warning',
  needs_review: 'warning',
  waiting_for_resource: 'warning',
  configuration_required: 'warning',
  failed: 'error',
  error: 'error',
  missing: 'error',
  invalid: 'error',
  dead_letter: 'error',
  disabled: 'default',
  cancelled: 'default',
};

const labels: Record<string, string> = {
  ready: '就绪',
  healthy: '健康',
  succeeded: '成功',
  success: '成功',
  passed: '通过',
  fresh: '新鲜',
  confirmed: '已确认',
  verified: '已校验',
  running: '运行中',
  refreshing: '刷新中',
  pending: '等待中',
  preparing: '准备中',
  testing: '测试中',
  queued: '排队中',
  created: '已创建',
  manual: '等待人工',
  scheduled: '已计划',
  skipped: '已跳过',
  discovered: '待确认',
  unknown: '结果待核对',
  degraded: '已降级',
  stale: '已过期',
  needs_review: '需复核',
  waiting_for_resource: '等待资源',
  configuration_required: '需配置',
  failed: '失败',
  error: '同步错误',
  missing: '本次未发现',
  invalid: '无效',
  dead_letter: '需人工处理',
  disabled: '已禁用',
  cancelled: '已取消',
};

export function StatusTag({ status }: { status: string }) {
  return <Tag color={colors[status] ?? 'default'}>{labels[status] ?? status}</Tag>;
}
