-- 季度 AI 生成必须能追溯到所属评审；确认记录保存可重建的完整冻结正文，而不只保存摘要哈希。
ALTER TABLE "ai_generation" ADD COLUMN "quarterly_review_id" TEXT;
ALTER TABLE "ai_generation" ADD COLUMN "base_quarterly_review_version" INTEGER;
ALTER TABLE "ai_generation" ADD COLUMN "adopted_narrative_version_id" TEXT;

ALTER TABLE "quarterly_review_confirmation" ADD COLUMN "achievements_snapshot_json" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "quarterly_review_confirmation" ADD COLUMN "scores_snapshot_json" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "quarterly_review_confirmation" ADD COLUMN "template_snapshot_json" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "quarterly_review_confirmation" ADD COLUMN "narrative_snapshot_json" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "quarterly_review_confirmation" ADD COLUMN "completeness_snapshot_json" TEXT NOT NULL DEFAULT '{}';

CREATE INDEX "ai_generation_quarterly_review_id_purpose_created_at_idx" ON "ai_generation"("quarterly_review_id", "purpose", "created_at");
CREATE UNIQUE INDEX "ai_generation_adopted_narrative_version_id_key" ON "ai_generation"("adopted_narrative_version_id");

-- SQLite 不能通过 ALTER TABLE 追加外键，因此用写入触发器实施同等的引用完整性约束。
CREATE TRIGGER "ai_generation_quarterly_review_fk_insert" BEFORE INSERT ON "ai_generation"
WHEN NEW."quarterly_review_id" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "quarterly_review" WHERE "id" = NEW."quarterly_review_id")
BEGIN SELECT RAISE(ABORT, 'quarterly review does not exist'); END;

DROP TRIGGER "ai_generation_validate_insert";
DROP TRIGGER "ai_generation_immutable_update";

-- 周报建议与季度自评建议共享生成账本，但分别绑定各自的基线与采纳版本。
CREATE TRIGGER "ai_generation_validate_insert" BEFORE INSERT ON "ai_generation" BEGIN SELECT CASE
  WHEN NEW."provider_config_version" <= 0 OR (NEW."base_report_version" IS NOT NULL AND NEW."base_report_version" <= 0) OR (NEW."base_quarterly_review_version" IS NOT NULL AND NEW."base_quarterly_review_version" <= 0) THEN RAISE(ABORT, 'ai_generation base version is invalid')
  WHEN NEW."purpose" NOT IN ('weekly_report','evidence_suggestion','quarterly_review','score_suggestion') OR NEW."protocol" NOT IN ('openai_compatible','anthropic','gemini') OR NEW."status" NOT IN ('succeeded','failed','blocked') OR NEW."retention_mode" NOT IN ('hash_only','sanitized_input') THEN RAISE(ABORT, 'ai_generation enum is invalid')
  WHEN NEW."retention_mode" = 'hash_only' AND NEW."sanitized_input_json" IS NOT NULL THEN RAISE(ABORT, 'hash_only ai_generation cannot retain sanitized input')
  WHEN NEW."duration_ms" IS NOT NULL AND NEW."duration_ms" < 0 THEN RAISE(ABORT, 'ai_generation duration is invalid')
  WHEN json_valid(NEW."requested_fields_json") = 0 OR json_type(NEW."requested_fields_json") <> 'array' OR json_valid(NEW."input_refs_json") = 0 OR json_type(NEW."input_refs_json") <> 'array' OR json_valid(NEW."input_categories_json") = 0 OR json_type(NEW."input_categories_json") <> 'array' OR json_valid(NEW."removed_categories_json") = 0 OR json_type(NEW."removed_categories_json") <> 'array' OR json_valid(NEW."usage_json") = 0 OR json_type(NEW."usage_json") <> 'object' OR json_valid(NEW."security_blocks_json") = 0 OR json_type(NEW."security_blocks_json") <> 'array' THEN RAISE(ABORT, 'ai_generation JSON shape is invalid')
  WHEN NEW."status" = 'succeeded' AND (NEW."sanitized_input_hash" IS NULL OR NEW."raw_output" IS NULL OR NEW."parsed_output_json" IS NULL OR json_valid(NEW."parsed_output_json") = 0 OR NEW."error_code" IS NOT NULL) THEN RAISE(ABORT, 'succeeded ai_generation is incomplete')
  WHEN NEW."status" = 'failed' AND NEW."error_code" IS NULL THEN RAISE(ABORT, 'failed ai_generation requires error_code')
  WHEN NEW."status" = 'blocked' AND json_array_length(NEW."security_blocks_json") = 0 THEN RAISE(ABORT, 'blocked ai_generation requires security categories')
  WHEN NEW."adoption_status" NOT IN ('pending','adopted','rejected','not_applicable') THEN RAISE(ABORT, 'ai_generation adoption status is invalid')
  WHEN NEW."adoption_status" = 'pending' AND NOT ((NEW."purpose" = 'weekly_report' AND NEW."report_id" IS NOT NULL AND NEW."base_version_id" IS NOT NULL AND NEW."base_report_version" IS NOT NULL) OR (NEW."purpose" = 'quarterly_review' AND NEW."quarterly_review_id" IS NOT NULL AND NEW."base_quarterly_review_version" IS NOT NULL)) THEN RAISE(ABORT, 'pending ai_generation is incomplete')
  WHEN NEW."adoption_status" = 'adopted' AND (NEW."status" <> 'succeeded' OR NEW."decided_at" IS NULL OR (NEW."adopted_version_id" IS NULL AND NEW."adopted_narrative_version_id" IS NULL)) THEN RAISE(ABORT, 'adopted ai_generation is incomplete')
  WHEN NEW."adoption_status" IN ('pending','not_applicable','rejected') AND (NEW."adopted_version_id" IS NOT NULL OR NEW."adopted_narrative_version_id" IS NOT NULL) THEN RAISE(ABORT, 'non-adopted ai_generation cannot reference adopted content')
  WHEN NEW."report_id" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "weekly_report" WHERE "id" = NEW."report_id" AND "owner_profile_id" = NEW."owner_profile_id") THEN RAISE(ABORT, 'ai_generation report owner mismatch')
  WHEN NEW."base_version_id" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "weekly_report_version" WHERE "id" = NEW."base_version_id" AND "report_id" = NEW."report_id") THEN RAISE(ABORT, 'ai_generation base version mismatch')
  WHEN NEW."quarterly_review_id" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "quarterly_review" WHERE "id" = NEW."quarterly_review_id" AND "owner_profile_id" = NEW."owner_profile_id") THEN RAISE(ABORT, 'ai_generation quarterly review owner mismatch')
END; END;

CREATE TRIGGER "ai_generation_immutable_update" BEFORE UPDATE ON "ai_generation" BEGIN SELECT CASE WHEN
  NEW."id" IS NOT OLD."id" OR NEW."owner_profile_id" IS NOT OLD."owner_profile_id" OR NEW."provider_connection_id" IS NOT OLD."provider_connection_id" OR NEW."provider_config_version" IS NOT OLD."provider_config_version" OR NEW."report_id" IS NOT OLD."report_id" OR NEW."quarterly_review_id" IS NOT OLD."quarterly_review_id" OR NEW."base_version_id" IS NOT OLD."base_version_id" OR NEW."base_report_version" IS NOT OLD."base_report_version" OR NEW."base_quarterly_review_version" IS NOT OLD."base_quarterly_review_version" OR NEW."purpose" IS NOT OLD."purpose" OR NEW."prompt_template_version" IS NOT OLD."prompt_template_version" OR NEW."sanitization_policy_version" IS NOT OLD."sanitization_policy_version" OR NEW."retention_mode" IS NOT OLD."retention_mode" OR NEW."requested_fields_json" IS NOT OLD."requested_fields_json" OR NEW."input_refs_json" IS NOT OLD."input_refs_json" OR NEW."input_categories_json" IS NOT OLD."input_categories_json" OR NEW."removed_categories_json" IS NOT OLD."removed_categories_json" OR NEW."sanitized_input_hash" IS NOT OLD."sanitized_input_hash" OR NEW."sanitized_input_json" IS NOT OLD."sanitized_input_json" OR NEW."raw_output" IS NOT OLD."raw_output" OR NEW."parsed_output_json" IS NOT OLD."parsed_output_json" OR NEW."protocol" IS NOT OLD."protocol" OR NEW."model" IS NOT OLD."model" OR NEW."provider_request_id" IS NOT OLD."provider_request_id" OR NEW."stop_reason" IS NOT OLD."stop_reason" OR NEW."usage_json" IS NOT OLD."usage_json" OR NEW."duration_ms" IS NOT OLD."duration_ms" OR NEW."status" IS NOT OLD."status" OR NEW."error_code" IS NOT OLD."error_code" OR NEW."security_blocks_json" IS NOT OLD."security_blocks_json" OR NEW."created_by" IS NOT OLD."created_by" OR NEW."created_at" IS NOT OLD."created_at" OR NEW."completed_at" IS NOT OLD."completed_at" THEN RAISE(ABORT, 'ai_generation facts are immutable') END; SELECT CASE
    WHEN OLD."adoption_status" <> 'pending' THEN RAISE(ABORT, 'ai_generation adoption decision is final')
    WHEN NEW."adoption_status" NOT IN ('adopted','rejected') OR NEW."decided_at" IS NULL THEN RAISE(ABORT, 'ai_generation adoption transition is invalid')
    WHEN NEW."adoption_status" = 'adopted' AND NEW."purpose" = 'weekly_report' AND (NEW."adopted_version_id" IS NULL OR NEW."adopted_narrative_version_id" IS NOT NULL OR NOT EXISTS (SELECT 1 FROM "weekly_report_version" WHERE "id" = NEW."adopted_version_id" AND "report_id" = NEW."report_id" AND "ai_generation_id" = NEW."id")) THEN RAISE(ABORT, 'adopted weekly version does not derive from ai_generation')
    WHEN NEW."adoption_status" = 'adopted' AND NEW."purpose" = 'quarterly_review' AND (NEW."adopted_narrative_version_id" IS NULL OR NEW."adopted_version_id" IS NOT NULL OR NOT EXISTS (SELECT 1 FROM "review_narrative_version" WHERE "id" = NEW."adopted_narrative_version_id" AND "review_id" = NEW."quarterly_review_id" AND "ai_generation_id" = NEW."id" AND "origin" = 'manual')) THEN RAISE(ABORT, 'adopted narrative does not derive from ai_generation')
    WHEN NEW."adoption_status" = 'rejected' AND (NEW."adopted_version_id" IS NOT NULL OR NEW."adopted_narrative_version_id" IS NOT NULL) THEN RAISE(ABORT, 'rejected ai_generation cannot reference adopted content')
  END; END;

CREATE TRIGGER "review_narrative_version_validate_insert" BEFORE INSERT ON "review_narrative_version" BEGIN SELECT CASE WHEN NEW."version_no" < 1 OR NEW."origin" NOT IN ('rule','ai','manual') OR json_valid(NEW."content_json") <> 1 OR json_type(NEW."content_json") <> 'object' OR json_valid(NEW."change_summary_json") <> 1 OR length(NEW."source_snapshot_hash") <> 64 OR length(NEW."content_hash") <> 64 OR (NEW."parent_version_id" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "review_narrative_version" WHERE "id" = NEW."parent_version_id" AND "review_id" = NEW."review_id")) OR (NEW."origin" = 'ai' AND (NEW."ai_generation_id" IS NULL OR NOT EXISTS (SELECT 1 FROM "ai_generation" WHERE "id" = NEW."ai_generation_id" AND "quarterly_review_id" = NEW."review_id" AND "purpose" = 'quarterly_review' AND "status" = 'succeeded'))) OR (NEW."ai_generation_id" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "ai_generation" WHERE "id" = NEW."ai_generation_id" AND "quarterly_review_id" = NEW."review_id" AND "status" = 'succeeded')) THEN RAISE(ABORT, 'review_narrative_version values are invalid') END; END;

CREATE TRIGGER "quarterly_review_current_pointer_validate_update" BEFORE UPDATE ON "quarterly_review" BEGIN SELECT CASE WHEN (NEW."current_narrative_version_id" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "review_narrative_version" WHERE "id" = NEW."current_narrative_version_id" AND "review_id" = NEW."id")) OR (NEW."current_confirmation_id" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "quarterly_review_confirmation" WHERE "id" = NEW."current_confirmation_id" AND "review_id" = NEW."id" AND "status" = 'active')) THEN RAISE(ABORT, 'quarterly review current pointer is invalid') END; END;

CREATE TRIGGER "quarterly_confirmation_relationship_validate_insert" BEFORE INSERT ON "quarterly_review_confirmation" BEGIN SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM "quarterly_review" WHERE "id" = NEW."review_id" AND "metric_template_version_id" = NEW."metric_template_version_id" AND "current_narrative_version_id" = NEW."narrative_version_id") OR NOT EXISTS (SELECT 1 FROM "review_narrative_version" WHERE "id" = NEW."narrative_version_id" AND "review_id" = NEW."review_id") THEN RAISE(ABORT, 'quarterly confirmation relationship is invalid') END; END;

DROP TRIGGER "quarterly_confirmation_validate_insert";
DROP TRIGGER "quarterly_confirmation_validate_update";

CREATE TRIGGER "quarterly_confirmation_validate_insert" BEFORE INSERT ON "quarterly_review_confirmation" BEGIN SELECT CASE WHEN NEW."status" <> 'active' OR length(NEW."snapshot_hash") <> 64 OR length(NEW."achievements_hash") <> 64 OR length(NEW."scores_hash") <> 64 OR json_valid(NEW."achievements_snapshot_json") <> 1 OR json_valid(NEW."scores_snapshot_json") <> 1 OR json_valid(NEW."template_snapshot_json") <> 1 OR json_valid(NEW."narrative_snapshot_json") <> 1 OR json_valid(NEW."completeness_snapshot_json") <> 1 OR json_valid(NEW."calculation_json") <> 1 OR json_valid(NEW."completeness_ack_json") <> 1 THEN RAISE(ABORT, 'quarterly_review_confirmation values are invalid') END; END;

CREATE TRIGGER "quarterly_confirmation_validate_update" BEFORE UPDATE ON "quarterly_review_confirmation" BEGIN SELECT CASE WHEN OLD."status" <> 'active' OR NEW."status" <> 'invalidated' OR NEW."invalidated_at" IS NULL OR length(trim(COALESCE(NEW."invalidation_reason", ''))) < 1 OR NEW."snapshot_hash" <> OLD."snapshot_hash" OR NEW."achievements_hash" <> OLD."achievements_hash" OR NEW."scores_hash" <> OLD."scores_hash" OR NEW."calculation_json" <> OLD."calculation_json" OR NEW."achievements_snapshot_json" <> OLD."achievements_snapshot_json" OR NEW."scores_snapshot_json" <> OLD."scores_snapshot_json" OR NEW."template_snapshot_json" <> OLD."template_snapshot_json" OR NEW."narrative_snapshot_json" <> OLD."narrative_snapshot_json" OR NEW."completeness_snapshot_json" <> OLD."completeness_snapshot_json" OR NEW."completeness_ack_json" <> OLD."completeness_ack_json" THEN RAISE(ABORT, 'quarterly_review_confirmation transition is invalid') END; END;
